-- ============================================================
-- 018: Imágenes y publicaciones de demostración por categoría
-- - Agrega fotos a las publicaciones que no tenían
-- - Quita 3 imágenes rotas de Unsplash
-- - Pasa tus publicaciones de music/home a categorías que existen en la app
-- - Crea publicaciones de demo para que cada categoría tenga al menos 4 con foto
-- Fotos: Wikimedia Commons (licencias libres)
-- Todo queda a nombre de Norlys Castañeda; no modifica publicaciones de otros usuarios.
-- Se puede ejecutar más de una vez sin duplicar datos.
-- ============================================================
BEGIN;

-- 1) Categorías que no existen en la app
UPDATE public.listings SET category = 'art', subcategory = 'Música' WHERE category = 'music' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a';
UPDATE public.listings SET category = 'electronics', subcategory = 'Electrodomésticos' WHERE category = 'home' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a';

-- 2) Imágenes rotas (404)
UPDATE public.listings l
SET images = COALESCE((
  SELECT jsonb_agg(e ORDER BY (e->>'order')::int)
  FROM jsonb_array_elements(l.images) e
  WHERE e->>'url' NOT LIKE '%1556906781-9a414e2a7735%'
    AND e->>'url' NOT LIKE '%1576435728678-68d0fbf94946%'
    AND e->>'url' NOT LIKE '%1531722569936-825d4eaa6617%'
), '[]'::jsonb)
WHERE l.user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND (l.images::text LIKE '%1556906781-9a414e2a7735%'
   OR l.images::text LIKE '%1576435728678-68d0fbf94946%'
   OR l.images::text LIKE '%1531722569936-825d4eaa6617%');

-- 3) Fotos para publicaciones que no tenían
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/96/Dell_Inspiron_2200%261300.jpg/960px-Dell_Inspiron_2200%261300.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a8/Dell_inspiron_700m.jpg/960px-Dell_inspiron_700m.jpg","order":1}]'::jsonb WHERE title = 'Laptop Dell Inspiron' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/76/Nintendo-Switch-Console-Docked-wJoyConRB.jpg/960px-Nintendo-Switch-Console-Docked-wJoyConRB.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/20/Nintendo_switch_lite_blue.jpg/960px-Nintendo_switch_lite_blue.jpg","order":1}]'::jsonb WHERE title = 'Nintendo Switch' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1d/Samsung_LED_TV.jpg/960px-Samsung_LED_TV.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2e/Samsung_Series_5%2C_Indonesia_20140422.jpg/960px-Samsung_Series_5%2C_Indonesia_20140422.jpg","order":1}]'::jsonb WHERE title = 'TV Samsung 50' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/28/Dirt_jump_IMG_7609.jpg/960px-Dirt_jump_IMG_7609.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/08/Freestyle_BMX_bike_2019-04-05_%281%29.jpg/960px-Freestyle_BMX_bike_2019-04-05_%281%29.jpg","order":1}]'::jsonb WHERE title = 'Bicicleta BMX' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ce/Trek_4500_mountain_bike_McDonald%27s_restaurant_Broad_Street_Lyndonville_VT_June_2016.jpg/960px-Trek_4500_mountain_bike_McDonald%27s_restaurant_Broad_Street_Lyndonville_VT_June_2016.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/84/Mountain_bike_downhill_05.jpg/960px-Mountain_bike_downhill_05.jpg","order":1}]'::jsonb WHERE title = 'Bicicleta Trek' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7e/PS4-Console-wDS4.jpg/960px-PS4-Console-wDS4.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/52/Sony-PlayStation-4-PS4-Console-FL.jpg/960px-Sony-PlayStation-4-PS4-Console-FL.jpg","order":1}]'::jsonb WHERE title = 'PlayStation 4' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/59/INLINE_SKATE.jpg/960px-INLINE_SKATE.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d8/Inline_skate_boot%2C_frame%2C_wheels%2C_bearings%2C_axle%2C_angle_view_2.jpg/960px-Inline_skate_boot%2C_frame%2C_wheels%2C_bearings%2C_axle%2C_angle_view_2.jpg","order":1}]'::jsonb WHERE title = 'Patines Roller' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8c/Bosch_PSB_550_RE_drill.JPG/960px-Bosch_PSB_550_RE_drill.JPG","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/88/Bosch_11236VS_loaded.jpg/960px-Bosch_11236VS_loaded.jpg","order":1}]'::jsonb WHERE title = 'Taladro Bosch' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/28/Wright_dining_table_-_HNT.jpg/960px-Wright_dining_table_-_HNT.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/af/View_of_the_%22Lost_Dining_Table_and_Chairs%22_in_Eltham_Palace_-_geograph.org.uk_-_5797282.jpg/960px-View_of_the_%22Lost_Dining_Table_and_Chairs%22_in_Eltham_Palace_-_geograph.org.uk_-_5797282.jpg","order":1}]'::jsonb WHERE title = 'Juego de Comedor' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/61/HP_Pavilion_G7-1317cl_Notebook_PC.jpeg/960px-HP_Pavilion_G7-1317cl_Notebook_PC.jpeg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/34/HP_Compaq_6730b.jpg/960px-HP_Compaq_6730b.jpg","order":1}]'::jsonb WHERE title = 'Laptop HP' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/39/1958_Fender_Stratocaster_%28%2432%2C000%29%2C_Vintage_Guitar_show%2C_SXSW2009.jpg/960px-1958_Fender_Stratocaster_%28%2432%2C000%29%2C_Vintage_Guitar_show%2C_SXSW2009.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1a/Rear_fender_stratocaster_Starcaster.jpg/960px-Rear_fender_stratocaster_Starcaster.jpg","order":1}]'::jsonb WHERE title = 'Guitarra Fender' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a2/English_Class_in_School.jpg/960px-English_Class_in_School.jpg","order":0}]'::jsonb WHERE title = 'Clases Inglés' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/Yamaha_FG403S_Dreadnought_Style_Acoustic_Guitar_%282002%29.jpg/960px-Yamaha_FG403S_Dreadnought_Style_Acoustic_Guitar_%282002%29.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Close_up_of_an_acoustic_guitar_being_played.jpg/960px-Close_up_of_an_acoustic_guitar_being_played.jpg","order":1}]'::jsonb WHERE title = 'Guitarra Yamaha' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/73/Harry_Potter_books_with_cat.jpg/960px-Harry_Potter_books_with_cat.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0e/Harry_Potter_books_in_Georgian1768.jpg/960px-Harry_Potter_books_in_Georgian1768.jpg","order":1}]'::jsonb WHERE title = 'Colección Harry Potter' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/88/Canon_EOS_R5.jpg/960px-Canon_EOS_R5.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dd/Canon_EOS_RebelGp2.jpg/960px-Canon_EOS_RebelGp2.jpg","order":1}]'::jsonb WHERE title = 'Cámara Canon' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/27/Apple_iPhone_12_Pro_-_Cameras_%2850535314721%29.jpg/960px-Apple_iPhone_12_Pro_-_Cameras_%2850535314721%29.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/84/A_red_iPhone_12.jpg/960px-A_red_iPhone_12.jpg","order":1}]'::jsonb WHERE title = 'iPhone 12 Pro' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/32/PAX_South_2016_-_DXRacer_chairs_%2824353747389%29.jpg/960px-PAX_South_2016_-_DXRacer_chairs_%2824353747389%29.jpg","order":0}]'::jsonb WHERE title = 'Silla Gamer' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d3/Air_Fryer_2020.jpg/960px-Air_Fryer_2020.jpg","order":0}]'::jsonb WHERE title = 'Aire Fryer' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7e/LG_L194WT-SF_LCD_monitor.jpg/960px-LG_L194WT-SF_LCD_monitor.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/47/LG_Flatron_IPS231P-BN-2753.jpg/960px-LG_Flatron_IPS231P-BN-2753.jpg","order":1}]'::jsonb WHERE title = 'Monitor LG 27' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/62/Zempl%C3%ADn_Museum_in_Michalovce_-_History_permanent_exhibition_-_Dining_room_-_Late_Art_Nouveau_furniture_set%2C_dining_table%2C_chairs%2C_early_20th_century_01.jpg/960px-Zempl%C3%ADn_Museum_in_Michalovce_-_History_permanent_exhibition_-_Dining_room_-_Late_Art_Nouveau_furniture_set%2C_dining_table%2C_chairs%2C_early_20th_century_01.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/East_Slovak_Museum_in_Ko%C5%A1ice_-_Experience_Gothic_exhibit_-_Wooden_dining_table%2C_15th_century%2C_Spi%C5%A1_region.jpg/960px-East_Slovak_Museum_in_Ko%C5%A1ice_-_Experience_Gothic_exhibit_-_Wooden_dining_table%2C_15th_century%2C_Spi%C5%A1_region.jpg","order":1}]'::jsonb WHERE title = 'Mesa Comedor' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;
UPDATE public.listings SET images = '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5b/MacBook_M1.jpg/960px-MacBook_M1.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Macbook_Air_2020_%28M1%29_-_1.jpg/960px-Macbook_Air_2020_%28M1%29_-_1.jpg","order":1}]'::jsonb WHERE title = 'MacBook Air M1' AND user_id = 'ae465756-8673-43a4-aac7-7d9710877a7a' AND images = '[]'::jsonb;

-- 4) Publicaciones de demostración (no se duplican si ya existen)
INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Café de Boconó molido — 3 paquetes de 500 g', 'Café de altura cultivado en Boconó, tostado artesanal y molido. Paquetes sellados, cosecha reciente.', 'good', 'food', 'Café y cacao', 'new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c5/Roasted_coffee_beans.jpg/960px-Roasted_coffee_beans.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f0/Coffee_beans_roasted.jpg/960px-Coffee_beans_roasted.jpg","order":1}]'::jsonb, ARRAY['cafe', 'boconó', 'artesanal']::text[], 'Queso de mano, miel o frutas de temporada', 15, 9.3149, -70.6084, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":3,"waste_reduced_kg":0.5,"estimated_value_usd":15}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Café de Boconó molido — 3 paquetes de 500 g');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Cesta de frutas y verduras de los Andes trujillanos', 'Papas, zanahorias, fresas, mora y cilantro recién cosechados en finca familiar. Ideal para la semana.', 'good', 'food', 'Frutas y verduras', 'new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/93/Fruits_and_Vegetables_in_Boquete%2C_Panama.jpg/960px-Fruits_and_Vegetables_in_Boquete%2C_Panama.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/85/Fresh_beans%2C_water_melons%2C_cabbage%2C_green_vegetables_and_oranges.jpg/960px-Fresh_beans%2C_water_melons%2C_cabbage%2C_green_vegetables_and_oranges.jpg","order":1}]'::jsonb, ARRAY['frutas', 'verduras', 'organico']::text[], 'Granos, arroz, aceite o productos de limpieza', 12, 9.3219, -70.6014, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":3,"waste_reduced_kg":0.5,"estimated_value_usd":12}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Cesta de frutas y verduras de los Andes trujillanos');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Queso de mano y suero artesanal', 'Queso de mano fresco (2 kg) y suero preparado en casa. Entrega el mismo día de elaboración.', 'good', 'food', 'Lácteos', 'new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ec/Cheese_from_village.jpg/960px-Cheese_from_village.jpg","order":0}]'::jsonb, ARRAY['queso', 'lacteos', 'artesanal']::text[], 'Café, pan casero o vegetales', 14, 9.3139, -70.6094, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":3,"waste_reduced_kg":0.5,"estimated_value_usd":14}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Queso de mano y suero artesanal');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Caraotas negras y frijoles — 5 kg', 'Granos limpios de cosecha propia, secos y listos para cocinar. Empacados en bolsas de 1 kg.', 'good', 'food', 'Granos y cereales', 'new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ce/Black_Turtle_Bean.jpg/960px-Black_Turtle_Bean.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/2015_1012_Preserved_black_beans_douchi_close-up.jpg/960px-2015_1012_Preserved_black_beans_douchi_close-up.jpg","order":1}]'::jsonb, ARRAY['granos', 'caraotas', 'cosecha']::text[], 'Harina de maíz, azúcar o café', 10, 9.3209, -70.6024, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":3,"waste_reduced_kg":0.5,"estimated_value_usd":10}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Caraotas negras y frijoles — 5 kg');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Juegos de mesa: Monopoly + Jenga + UNO', 'Tres juegos completos, todas las piezas. Perfectos para reuniones familiares.', 'good', 'toys', 'Juegos de mesa', 'like_new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cc/Monopoly_board_game.jpg/960px-Monopoly_board_game.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/78/Monopoly_board_on_white_bg.jpg/960px-Monopoly_board_on_white_bg.jpg","order":1}]'::jsonb, ARRAY['juegos', 'mesa', 'familia']::text[], 'Libros infantiles o rompecabezas', 30, 9.3129, -70.6104, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":30}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Juegos de mesa: Monopoly + Jenga + UNO');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Set de LEGO Classic — 900 piezas', 'Caja de LEGO Classic con 900 piezas de colores y manual de ideas. Sin piezas faltantes.', 'good', 'toys', 'Juguetes educativos', 'good', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/32/Lego_Color_Bricks.jpg/960px-Lego_Color_Bricks.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Lego_bricks.jpg/960px-Lego_bricks.jpg","order":1}]'::jsonb, ARRAY['lego', 'niños', 'creatividad']::text[], 'Ropa infantil talla 8 o útiles escolares', 45, 9.3199, -70.6034, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":45}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Set de LEGO Classic — 900 piezas');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Peluches y juguetes para bebé — lote de 10', 'Peluches lavados y desinfectados, sonajeros y mordedores. Bebé ya creció.', 'good', 'toys', 'Juguetes para bebés', 'good', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3a/60_Jahre_Allgemeine_Erkl%C3%A4rung_der_Menschenrechte_%283084670759%29.jpg/960px-60_Jahre_Allgemeine_Erkl%C3%A4rung_der_Menschenrechte_%283084670759%29.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/18/2023-03-01_12-28-00_peluchesTDF.jpg/960px-2023-03-01_12-28-00_peluchesTDF.jpg","order":1}]'::jsonb, ARRAY['bebe', 'peluches', 'lote']::text[], 'Pañales talla G o ropa de bebé 12-18 meses', 20, 9.3269, -70.6114, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":20}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Peluches y juguetes para bebé — lote de 10');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Rompecabezas de 1000 piezas — paisajes', 'Dos rompecabezas armados una sola vez, completos y guardados en su caja original.', 'good', 'toys', 'Rompecabezas', 'like_new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/11/Jigsaw_puzzle_in_progress.jpg/960px-Jigsaw_puzzle_in_progress.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0a/Red_jigsaw_puzzle_piece_on_green_pieces.jpg/960px-Red_jigsaw_puzzle_piece_on_green_pieces.jpg","order":1}]'::jsonb, ARRAY['rompecabezas', 'puzzle', 'hobby']::text[], 'Otros rompecabezas o libros de novela', 18, 9.3189, -70.6044, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":18}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Rompecabezas de 1000 piezas — paisajes');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Kit de maquillaje nuevo — paleta, labiales y brochas', 'Paleta de sombras, 3 labiales y set de 8 brochas. Todo sellado, regalo repetido.', 'good', 'beauty', 'Maquillaje', 'new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/22/Various_makeup_brushes.jpg/960px-Various_makeup_brushes.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2b/Makeup_Brushes_-_%CE%A0%CE%B9%CE%BD%CE%AD%CE%BB%CE%B1_%CE%BC%CE%B1%CE%BA%CE%B9%CE%B3%CE%B9%CE%AC%CE%B6.JPG/960px-Makeup_Brushes_-_%CE%A0%CE%B9%CE%BD%CE%AD%CE%BB%CE%B1_%CE%BC%CE%B1%CE%BA%CE%B9%CE%B3%CE%B9%CE%AC%CE%B6.JPG","order":1}]'::jsonb, ARRAY['maquillaje', 'brochas', 'nuevo']::text[], 'Perfume, ropa de mujer talla S o skincare', 35, 9.3259, -70.6124, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":35}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Kit de maquillaje nuevo — paleta, labiales y brochas');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Perfume importado 100 ml (usado 10%)', 'Fragancia floral importada, frasco de 100 ml casi lleno con su caja.', 'good', 'beauty', 'Perfumes', 'like_new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/79/A_Suma-perfume_by_Coty.1.jpg/960px-A_Suma-perfume_by_Coty.1.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/91/Perfume_set_from_Sovjetunio_cca_1965.jpg/960px-Perfume_set_from_Sovjetunio_cca_1965.jpg","order":1}]'::jsonb, ARRAY['perfume', 'fragancia', 'importado']::text[], 'Zapatos talla 37 o cartera', 40, 9.3179, -70.6054, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":40}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Perfume importado 100 ml (usado 10%)');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Secador y plancha de cabello profesional', 'Secador de 2000 W y plancha de cerámica con control de temperatura. Funcionan perfecto.', 'good', 'beauty', 'Cuidado del cabello', 'good', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1f/HITACHI_HAIR_DRYER_HD-1650.jpg/960px-HITACHI_HAIR_DRYER_HD-1650.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7c/Hair_straightener_TTH2510_by_Tescom_%282015-09-19%29.JPG/960px-Hair_straightener_TTH2510_by_Tescom_%282015-09-19%29.JPG","order":1}]'::jsonb, ARRAY['cabello', 'secador', 'plancha']::text[], 'Licuadora, ropa o electrodomésticos pequeños', 38, 9.3249, -70.5984, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":38}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Secador y plancha de cabello profesional');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Jabones artesanales de sábila y avena — 12 unidades', 'Jabones naturales hechos a mano con sábila, avena y aceites esenciales. Sin químicos.', 'good', 'beauty', 'Natural y orgánico', 'new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4c/Bars_of_pure_Marseille_and_Aleppo_soap%2C_2024.jpg/960px-Bars_of_pure_Marseille_and_Aleppo_soap%2C_2024.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9b/Handmade_soap_cropped_and_simplified.jpg/960px-Handmade_soap_cropped_and_simplified.jpg","order":1}]'::jsonb, ARRAY['jabon', 'natural', 'artesanal']::text[], 'Frutas, café o productos de limpieza', 15, 9.3169, -70.6064, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":15}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Jabones artesanales de sábila y avena — 12 unidades');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Moto Bera 150 cc — año 2019', 'Moto en buen estado, papeles al día, cauchos nuevos. Ideal para trabajar en la ciudad.', 'good', 'vehicles', 'Motos', 'good', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/8/80/James_Cadet_J15_150cc_%281954%29.jpg/960px-James_Cadet_J15_150cc_%281954%29.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a2/Francis-Barnett_Plover_150cc_%281959%29.jpg/960px-Francis-Barnett_Plover_150cc_%281959%29.jpg","order":1}]'::jsonb, ARRAY['moto', 'bera', 'transporte']::text[], 'Laptop + teléfono, o mercancía para emprendimiento', 900, 9.3239, -70.5994, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":50,"waste_reduced_kg":20,"estimated_value_usd":900}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Moto Bera 150 cc — año 2019');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Juego de 4 rines de aluminio rin 15', 'Rines de aluminio rin 15, 4 huecos, sin golpes ni soldaduras.', 'good', 'vehicles', 'Repuestos', 'like_new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/91/Hamann._%286744609419%29.jpg/960px-Hamann._%286744609419%29.jpg","order":0}]'::jsonb, ARRAY['rines', 'repuestos', 'carro']::text[], 'Batería de carro o herramientas', 220, 9.3159, -70.6074, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":50,"waste_reduced_kg":20,"estimated_value_usd":220}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Juego de 4 rines de aluminio rin 15');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Cauchos 185/65 R14 — 70% de vida útil', 'Cuatro cauchos marca reconocida con buen labrado, sin parches.', 'good', 'vehicles', 'Neumáticos', 'good', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/Dirty_car_tires.jpg/960px-Dirty_car_tires.jpg","order":0}]'::jsonb, ARRAY['cauchos', 'neumaticos', 'carro']::text[], 'Aceite de motor, filtros o repuestos', 120, 9.3229, -70.6004, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":50,"waste_reduced_kg":20,"estimated_value_usd":120}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Cauchos 185/65 R14 — 70% de vida útil');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Tensiómetro digital de brazo', 'Tensiómetro automático con memoria para 2 usuarios, incluye estuche y pilas.', 'good', 'health', 'Equipos médicos', 'like_new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Citizen_CH-437C_20110503.jpg/960px-Citizen_CH-437C_20110503.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Close-up_of_a_woman_using_a_blood_pressure_monitor.jpg/960px-Close-up_of_a_woman_using_a_blood_pressure_monitor.jpg","order":1}]'::jsonb, ARRAY['tensiometro', 'salud', 'medico']::text[], 'Medicamentos para la tensión (no vencidos) o alimentos', 25, 9.3149, -70.6084, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":25}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Tensiómetro digital de brazo');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Silla de ruedas plegable', 'Silla de ruedas de acero plegable, frenos funcionando, cojín incluido.', 'good', 'health', 'Movilidad', 'good', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/60/UNAwheel_Mini_Basic_wheelchair_power_add-on_02.jpg/960px-UNAwheel_Mini_Basic_wheelchair_power_add-on_02.jpg","order":0}]'::jsonb, ARRAY['silla de ruedas', 'movilidad']::text[], 'Andadera, muletas o lo que necesites para donar', 90, 9.3219, -70.6014, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":90}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Silla de ruedas plegable');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Plantas medicinales en matera: sábila, toronjil y menta', 'Cinco materas con plantas medicinales sanas, listas para el patio o balcón.', 'good', 'health', 'Plantas medicinales', 'new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/07/Aloe_vera_plant_in_flower_pot.jpg/960px-Aloe_vera_plant_in_flower_pot.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Aloevera-pottedplant.jpg/960px-Aloevera-pottedplant.jpg","order":1}]'::jsonb, ARRAY['plantas', 'medicinales', 'sabila']::text[], 'Semillas, abono o frutas', 12, 9.3139, -70.6094, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":12}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Plantas medicinales en matera: sábila, toronjil y menta');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Suculentas y cactus en materas de barro', 'Ocho suculentas y cactus en materas pequeñas de barro. Fáciles de cuidar.', 'good', 'other', 'Plantas', 'new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Succulent_Neighbors.jpg/960px-Succulent_Neighbors.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/20/Succulent_pot_collection.jpg/960px-Succulent_pot_collection.jpg","order":1}]'::jsonb, ARRAY['suculentas', 'cactus', 'plantas']::text[], 'Otras plantas, semillas o tierra abonada', 16, 9.3209, -70.6024, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":16}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Suculentas y cactus en materas de barro');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Colección de monedas y billetes venezolanos antiguos', 'Monedas de bolívar fuerte y billetes de distintas épocas, guardados en álbum.', 'good', 'other', 'Coleccionables', 'good', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7e/Few_old_coins_from_a_numismatic_collection.jpg/960px-Few_old_coins_from_a_numismatic_collection.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5c/Old-Indian-coins.JPG/960px-Old-Indian-coins.JPG","order":1}]'::jsonb, ARRAY['monedas', 'coleccion', 'historia']::text[], 'Libros de historia o coleccionables', 30, 9.3129, -70.6104, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":30}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Colección de monedas y billetes venezolanos antiguos');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Útiles escolares y de oficina — lote completo', 'Cuadernos, lápices, marcadores, carpetas y resaltadores. Nuevos, sobrantes de compra al mayor.', 'good', 'other', 'Material de oficina', 'new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/08/Colored_pencils_chevre.jpg/960px-Colored_pencils_chevre.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b1/Colouring_pencils.jpg/960px-Colouring_pencils.jpg","order":1}]'::jsonb, ARRAY['utiles', 'oficina', 'escolar']::text[], 'Ropa escolar o libros de texto', 22, 9.3199, -70.6034, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":22}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Útiles escolares y de oficina — lote completo');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Reparación de computadoras y teléfonos', 'Formateo, cambio de pantalla, limpieza interna y recuperación de datos. A domicilio en Valera.', 'service', 'services', 'Reparaciones', NULL, '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/57/Computer_repair_in_progress.jpg/960px-Computer_repair_in_progress.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fc/Reparatie_calculatoare_chisinau.jpg/960px-Reparatie_calculatoare_chisinau.jpg","order":1}]'::jsonb, ARRAY['reparacion', 'tecnico', 'computadoras']::text[], 'Alimentos, ropa o repuestos electrónicos', 25, 9.3269, -70.6114, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":25}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Reparación de computadoras y teléfonos');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Arreglos de ropa y costura a medida', 'Ruedos, cierres, ajustes de talla y confección sencilla. Entrega en 3 días.', 'service', 'services', 'Corte y costura', NULL, '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b3/A_Tailor_Sewing_Clothes_in_Her_Shop.jpg/960px-A_Tailor_Sewing_Clothes_in_Her_Shop.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/African_tailor_sewing_a_leather_bag.jpg/960px-African_tailor_sewing_a_leather_bag.jpg","order":1}]'::jsonb, ARRAY['costura', 'ropa', 'arreglos']::text[], 'Telas, hilos o víveres', 10, 9.3189, -70.6044, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":10}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Arreglos de ropa y costura a medida');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Tareas dirigidas para primaria (matemáticas y lectura)', 'Apoyo escolar de lunes a viernes por la tarde, grupos pequeños de hasta 4 niños.', 'service', 'education', 'Primaria', NULL, '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a3/SAKURAKO_-_Homework_for_summer_vacation._%2820028533861%29.jpg/960px-SAKURAKO_-_Homework_for_summer_vacation._%2820028533861%29.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0e/School_girl_studying.JPG/960px-School_girl_studying.JPG","order":1}]'::jsonb, ARRAY['tareas', 'primaria', 'niños']::text[], 'Alimentos, útiles escolares o ropa infantil', 20, 9.3259, -70.6124, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":20}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Tareas dirigidas para primaria (matemáticas y lectura)');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Herramientas de jardinería — pala, rastrillo y tijeras', 'Kit de jardinería con pala, rastrillo, tijera de podar y guantes.', 'good', 'tools', 'Jardinería', 'good', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b1/R%C3%B6srath_Germany_Tool-shed-for-gardening-01.jpg/960px-R%C3%B6srath_Germany_Tool-shed-for-gardening-01.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4d/Leaf_rake_in_an_Australian_garden_1.jpg/960px-Leaf_rake_in_an_Australian_garden_1.jpg","order":1}]'::jsonb, ARRAY['jardineria', 'herramientas', 'huerto']::text[], 'Plantas, semillas o abono', 25, 9.3179, -70.6054, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":10,"waste_reduced_kg":3,"estimated_value_usd":25}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Herramientas de jardinería — pala, rastrillo y tijeras');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Novelas venezolanas: Doña Bárbara, Las lanzas coloradas y más', 'Cinco clásicos de la literatura venezolana en buen estado, ideales para el liceo.', 'good', 'books', 'Literatura venezolana', 'good', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/20/Old_Books_02.JPG/960px-Old_Books_02.JPG","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/Old_books_%28Unsplash%29.jpg/960px-Old_books_%28Unsplash%29.jpg","order":1}]'::jsonb, ARRAY['libros', 'literatura', 'venezuela']::text[], 'Libros de otros autores o útiles escolares', 20, 9.3249, -70.5984, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":2,"waste_reduced_kg":0.3,"estimated_value_usd":20}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Novelas venezolanas: Doña Bárbara, Las lanzas coloradas y más');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT 'ae465756-8673-43a4-aac7-7d9710877a7a', 'Semillas de hortalizas para huerto en casa', 'Sobres de semillas de tomate, pimentón, cilantro, lechuga y zanahoria. Ideales para empezar un huerto en el patio o en materas.', 'good', 'other', 'Semillas', 'new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/45/Packets_of_Vegetable_Seeds_at_Menards.jpg/960px-Packets_of_Vegetable_Seeds_at_Menards.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5e/Packets_of_Vegetable_Seeds.jpg/960px-Packets_of_Vegetable_Seeds.jpg","order":1}]'::jsonb, ARRAY['semillas', 'huerto', 'hortalizas']::text[], 'Plantas, abono o herramientas de jardinería', 10, 9.3169, -70.6064, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":10}'::jsonb
WHERE NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Semillas de hortalizas para huerto en casa');

-- 5) Recalcular publicaciones activas de cada usuario
UPDATE public.profiles p SET active_listings_count = (
  SELECT COUNT(*) FROM public.listings l WHERE l.user_id = p.id AND l.status = 'active'
) WHERE p.id = 'ae465756-8673-43a4-aac7-7d9710877a7a';

COMMIT;

-- Verificación: publicaciones activas con foto por categoría
SELECT category, COUNT(*) FILTER (WHERE jsonb_array_length(images) > 0) AS con_foto, COUNT(*) AS total
FROM public.listings WHERE status = 'active' GROUP BY category ORDER BY category;
