-- ============================================================
-- 019: Artículos de demostración para Rhonny Jaimes (rhonnyjaimes1@gmail.com)
-- 12 artículos nuevos en Valera, estado Trujillo, en categorías distintas.
-- Fotos: Wikimedia Commons (licencias libres).
-- Busca la cuenta por correo; si el correo no existe, no inserta nada.
-- Se puede ejecutar más de una vez sin duplicar datos.
-- ============================================================
BEGIN;

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com'), 'Libros de programación y bases de datos', 'Lote de libros de programación en Java, Python y SQL. Ideales para estudiantes de ingeniería.', 'good', 'books', 'Libros universitarios', 'good', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/Lingo%2C_Lingo%2C_Lingo_%28116957067%29.jpg/960px-Lingo%2C_Lingo%2C_Lingo_%28116957067%29.jpg","order":0}]'::jsonb, ARRAY['libros', 'programacion', 'ingenieria']::text[], 'Componentes de computadora o libros de redes', 35, 9.3105, -70.6083, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":2,"waste_reduced_kg":0.3,"estimated_value_usd":35}'::jsonb
WHERE (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Libros de programación y bases de datos');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com'), 'Escritorio de madera para estudio con gavetas', 'Escritorio de 120 × 60 cm con dos gavetas. Firme, sin daños, ideal para estudiar o trabajar.', 'good', 'furniture', 'Oficina', 'good', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b3/Desk%2C_writing_%28AM_1996.33.1-3%29.jpg/960px-Desk%2C_writing_%28AM_1996.33.1-3%29.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/LA2_Facit_chair_drawer.jpg/960px-LA2_Facit_chair_drawer.jpg","order":1}]'::jsonb, ARRAY['escritorio', 'estudio', 'madera']::text[], 'Silla de oficina, lámpara o monitor', 60, 9.3175, -70.6033, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":25,"waste_reduced_kg":10,"estimated_value_usd":60}'::jsonb
WHERE (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Escritorio de madera para estudio con gavetas');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com'), 'Cacao en polvo artesanal de Trujillo — 1 kg', 'Cacao puro tostado y molido de forma artesanal. Sin azúcar añadida. Empacado al vacío.', 'good', 'food', 'Café y cacao', 'new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d4/Cocoa-powder-1883108.jpg/960px-Cocoa-powder-1883108.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fe/Cocoa_Powder_and_Chocolate_on_Marble_Background.jpg/960px-Cocoa_Powder_and_Chocolate_on_Marble_Background.jpg","order":1}]'::jsonb, ARRAY['cacao', 'artesanal', 'trujillo']::text[], 'Café, miel o frutas', 12, 9.3115, -70.5983, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":3,"waste_reduced_kg":0.5,"estimated_value_usd":12}'::jsonb
WHERE (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Cacao en polvo artesanal de Trujillo — 1 kg');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com'), 'Control de Xbox One inalámbrico', 'Control original funcionando perfecto, con pilas recargables y cable USB.', 'good', 'toys', 'Videojuegos', 'good', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/67/Microsoft-Xbox-One-controller.jpg/960px-Microsoft-Xbox-One-controller.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/Xbox_One_Controller_Titanfall_Special_Edition.jpg/960px-Xbox_One_Controller_Titanfall_Special_Edition.jpg","order":1}]'::jsonb, ARRAY['xbox', 'control', 'videojuegos']::text[], 'Juegos de PS4 o audífonos', 30, 9.3185, -70.6043, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":30}'::jsonb
WHERE (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Control de Xbox One inalámbrico');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com'), 'Esmeril angular 4½" + discos de corte', 'Esmeril de 850 W con guarda, mango lateral y 5 discos de corte y desbaste.', 'good', 'tools', 'Herramientas eléctricas', 'like_new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/d/db/AngleGrinder.jpg/960px-AngleGrinder.jpg","order":0}]'::jsonb, ARRAY['esmeril', 'herramientas', 'construccion']::text[], 'Taladro inalámbrico o herramientas manuales', 40, 9.3125, -70.5993, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":10,"waste_reduced_kg":3,"estimated_value_usd":40}'::jsonb
WHERE (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Esmeril angular 4½" + discos de corte');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com'), 'Casco de moto certificado talla M', 'Casco integral con visor transparente, poco uso, sin golpes.', 'good', 'vehicles', 'Accesorios', 'like_new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/9/90/Full-Face_Helmet_9274.jpg/960px-Full-Face_Helmet_9274.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/7/78/Kreta_%28GR%29%2C_Rethymno%2C_Motorroller_--_2023_--_8344_%28crop%29.jpg/960px-Kreta_%28GR%29%2C_Rethymno%2C_Motorroller_--_2023_--_8344_%28crop%29.jpg","order":1}]'::jsonb, ARRAY['casco', 'moto', 'seguridad']::text[], 'Chaqueta de moto o guantes', 45, 9.3195, -70.6053, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":50,"waste_reduced_kg":20,"estimated_value_usd":45}'::jsonb
WHERE (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Casco de moto certificado talla M');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com'), 'Glucómetro digital con tiras reactivas', 'Glucómetro nuevo en su caja con 50 tiras y lancetas.', 'good', 'health', 'Equipos médicos', 'new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/37/Capteur_de_glyc%C3%A9mie_pour_personnes_diab%C3%A9tiques.jpg/960px-Capteur_de_glyc%C3%A9mie_pour_personnes_diab%C3%A9tiques.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/a/af/%2820250417%29_Blood_glucose_meter_09.jpg/960px-%2820250417%29_Blood_glucose_meter_09.jpg","order":1}]'::jsonb, ARRAY['glucometro', 'salud', 'diabetes']::text[], 'Tensiómetro o medicamentos no vencidos', 25, 9.3135, -70.6003, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":25}'::jsonb
WHERE (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Glucómetro digital con tiras reactivas');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com'), 'Máquina para cortar cabello profesional', 'Máquina recargable con 8 peines guía, tijera y capa. Ideal para barbería en casa.', 'good', 'beauty', 'Cuidado del cabello', 'like_new', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/36/2023_Trymer.jpg/960px-2023_Trymer.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e0/HITACHI_CL-8300.jpg/960px-HITACHI_CL-8300.jpg","order":1}]'::jsonb, ARRAY['barberia', 'cabello', 'maquina']::text[], 'Perfume, ropa o accesorios', 30, 9.3205, -70.6063, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":30}'::jsonb
WHERE (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Máquina para cortar cabello profesional');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com'), 'Jaula transportadora para perro mediano', 'Transportadora plástica con puerta metálica, ventilación lateral. Apta para viajes.', 'good', 'other', 'Mascotas', 'good', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f4/Dogtainers_Pet_Transport_Clipper_Cat_Cage_Plastic_Travel_Crate_Labelled.jpg/960px-Dogtainers_Pet_Transport_Clipper_Cat_Cage_Plastic_Travel_Crate_Labelled.jpg","order":0}]'::jsonb, ARRAY['mascotas', 'perro', 'transportadora']::text[], 'Alimento para mascotas o cama para perro', 28, 9.3145, -70.6013, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":28}'::jsonb
WHERE (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Jaula transportadora para perro mediano');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com'), 'Botas de trabajo punta de acero talla 42', 'Botas de seguridad en cuero, punta de acero, suela antideslizante. Usadas pocas veces.', 'good', 'clothing', 'Zapatos', 'good', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/26/Cleaning_my_nubuck_leather_work_boots.jpg/960px-Cleaning_my_nubuck_leather_work_boots.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2a/Boots_of_a_man.jpg/960px-Boots_of_a_man.jpg","order":1}]'::jsonb, ARRAY['botas', 'seguridad', 'trabajo']::text[], 'Zapatos deportivos talla 42 o herramientas', 35, 9.3215, -70.6073, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":8,"waste_reduced_kg":1.5,"estimated_value_usd":35}'::jsonb
WHERE (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Botas de trabajo punta de acero talla 42');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com'), 'Teclado electrónico de 61 teclas con atril', 'Teclado de 61 teclas con adaptador, atril y cientos de tonos. Perfecto para aprender.', 'good', 'art', 'Música', 'good', '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/Digital_Keyboards_Synergy2.jpg/960px-Digital_Keyboards_Synergy2.jpg","order":0},{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/6/63/Musical_Keyboard.jpg/960px-Musical_Keyboard.jpg","order":1}]'::jsonb, ARRAY['teclado', 'musica', 'casio']::text[], 'Guitarra eléctrica o amplificador', 70, 9.3155, -70.6023, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":70}'::jsonb
WHERE (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Teclado electrónico de 61 teclas con atril');

INSERT INTO public.listings (user_id, title, description, type, category, subcategory, condition, images, tags, looking_for, estimated_value_usd, latitude, longitude, city, state, status, eco_impact)
SELECT (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com'), 'Asesorías de programación para universitarios', 'Apoyo en Java, Python, bases de datos y proyectos de grado. Presencial en Valera u online.', 'service', 'education', 'Universidad', NULL, '[{"url":"https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ce/Zambian_kids_learning_how_to_use_computers.jpg/960px-Zambian_kids_learning_how_to_use_computers.jpg","order":0}]'::jsonb, ARRAY['programacion', 'asesorias', 'universidad']::text[], 'Alimentos, libros o equipos electrónicos', 15, 9.3225, -70.6083, 'Valera', 'Trujillo', 'active', '{"co2_saved_kg":5,"waste_reduced_kg":1,"estimated_value_usd":15}'::jsonb
WHERE (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com') IS NOT NULL AND NOT EXISTS (SELECT 1 FROM public.listings WHERE title = 'Asesorías de programación para universitarios');

-- Recalcular publicaciones activas de Rhonny
UPDATE public.profiles p SET active_listings_count = (
  SELECT COUNT(*) FROM public.listings l WHERE l.user_id = p.id AND l.status = 'active'
) WHERE p.id = (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com');

COMMIT;

-- Verificación: artículos activos de Rhonny por categoría
SELECT category, COUNT(*) AS articulos
FROM public.listings
WHERE user_id = (SELECT id FROM auth.users WHERE email = 'rhonnyjaimes1@gmail.com') AND status = 'active'
GROUP BY category ORDER BY category;
